import os
env = Environment(FORTRAN ='ifort', ENV = os.environ, CC='ifort')



#obj1 = Object(src, ENV=os.environ, FORTRAN='ifort', FORTRANFLAGS='-g')

#jjjobj1 = Object(['hello.f90', 'util.f90'])

#no_mod_files = lambda f: f[-4:] != '.mod'
#obj1 = filter(no_mod_files, obj1)

env.Program(target='bom', source=['hello.f90', 'util.f90'])

#env.Program(target = 'hello' , source = 'hello.f90') 
