BuildDir ('build', 'src')

import os
env = Environment(FORTRAN ='ifort', ENV = os.environ, CC='ifort')

# make mod file, and install it into lib dir

lib = env.Object ('build/util.f90')


#no_mod_files = lambda f: f[-4:] != '.mod'
#obj1 = filter(no_mod_files, obj1)

env.Program(target='bom', source=['build/hello.f90', 'build/util.f90'])

#env.Program(target = 'hello' , source = 'hello.f90') 

# FORTRANMOD
