import os

BuildDir ('build', 'src')

env = Environment(FORTRAN ='ifort', ENV = os.environ, CC='ifort')

#lib = env.Library('foo', 'build/util.f90')

env.Library('foo', 'build/util.f90', CCFLAGS=' -C')

#env.Object('build/hello.f90', LIBS=['foo'])

#Program(lib, prj)

